set(CMAKE_SYSTEM_NAME Linux)
SET (CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER $ENV{HORIZON_GCC_ROOT}aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER $ENV{HORIZON_GCC_ROOT}aarch64-linux-gnu-g++)
