FROM nvcr.io/nvidia/tritonserver:22.04-py3
LABEL maintainer="NVIDIA"
LABEL repository="tritonserver"

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-get update && apt-get -y install swig && apt-get -y install python3-dev && apt-get install -y cmake
RUN pip3 install torch==1.11.0 torchaudio==0.11.0 -i https://pypi.mirrors.ustc.edu.cn/simple/
RUN pip3 install -v kaldifeat pyyaml onnx -i https://pypi.mirrors.ustc.edu.cn/simple/

WORKDIR /workspace
RUN git clone https://github.com/Slyne/ctc_decoder.git && cd ctc_decoder/swig && bash setup.sh
COPY ./scripts scripts