FROM  nvcr.io/nvidia/tritonserver:22.03-py3-sdk
LABEL maintainer="NVIDIA"
LABEL repository="tritonserver"

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-get update && apt-get install -y libsndfile1
RUN pip3 install soundfile
WORKDIR /workspace
