acoustic_scale: 10.0
n_input_per_chunk: 50
default_beam: 17.0
max_active: 7000
determinize_lattice: True
max_batch_size: 800
num_channels: 800
frame_shift_seconds: 0.04
lm_scale: 5.0
word_ins_penalty: 0.0
