# network architecture
# encoder related
encoder: squeezeformer
encoder_conf:
    encoder_dim: 256
    output_size: 256    # dimension of attention
    attention_heads: 4
    num_blocks: 12      # the number of encoder blocks
    reduce_idx: 5
    recover_idx: 11
    pos_enc_layer_type: 'rel_pos'
    time_reduction_layer_type: 'conv1d'
    feed_forward_expansion_factor: 4
    input_dropout_rate: 0.1
    feed_forward_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    cnn_module_kernel: 31
    cnn_norm_type: layer_norm
    adaptive_scale: true
    normalize_before: false

# decoder related
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

tokenizer: bpe
tokenizer_conf:
  symbol_table_path: 'data/lang_char/train_960_unigram5000_units.txt'
  split_with_space: false
  bpe_path: 'data/lang_char/train_960_unigram5000.model'
  non_lang_syms_path: null
  is_multilingual: false
  num_languages: 1
  special_tokens:
    <blank>: 0
    <unk>: 1
    <sos>: 2
    <eos>: 2

ctc: ctc
ctc_conf:
  ctc_blank_id: 0

cmvn: global_cmvn
cmvn_conf:
  cmvn_file: 'data/train_960/global_cmvn'
  is_json_cmvn: true

# hybrid CTC/attention
model: asr_model
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1     # label smoothing option
    length_normalized_loss: false

# dataset related
dataset: asr
dataset_conf:
    filter_conf:
        max_length: 2000
        min_length: 50
        token_max_length: 400
        token_min_length: 1
        min_output_input_ratio: 0.0005
        max_output_input_ratio: 0.1
    resample_conf:
        resample_rate: 16000
    speed_perturb: true
    fbank_conf:
        num_mel_bins: 80
        frame_shift: 10
        frame_length: 25
        dither: 0.1
    spec_aug: true
    spec_aug_conf:
        num_t_mask: 2
        num_f_mask: 2
        max_t: 50
        max_f: 10
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    sort: true
    sort_conf:
        sort_size: 500  # sort_size should be less than shuffle_size
    batch_conf:
        batch_type: 'static' # static or dynamic
        batch_size: 12

grad_clip: 5
accum_grad: 4
max_epoch: 120
log_interval: 100

optim: adamw
optim_conf:
    lr: 1.e-3
    weight_decay: 4.e-5

scheduler: NoamHoldAnnealing
scheduler_conf:
    warmup_ratio: 0.2
    hold_ratio: 0.3
    max_steps: 87960
    decay_rate: 1.0
    min_lr: 1.e-5
