# network architecture
# encoder related
encoder: SanmEncoder
encoder_conf:
    output_size: 512    # dimension of attention
    attention_heads: 4
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 50      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: 'conv2d' # encoder input type, you can chose conv2d, conv2d6 and conv2d8
    normalize_before: true
    kernel_size: 11
    sanm_shfit: 0

input_dim: 80
output_dim: 8404
paraformer: true
is_json_cmvn: True
# decoder related
decoder: SanmDecoder
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 16
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1
    att_layer_num: 16
    kernel_size: 11
    sanm_shfit: 0

lfr_conf:
    lfr_m: 7
    lfr_n: 6

cif_predictor_conf:
    idim: 512
    threshold: 1.0
    l_order: 1
    r_order: 1
    tail_threshold: 0.45
    cnn_groups: 1
    residual: false

model_conf:
  ctc_weight: 0.0
