# network architecture
# encoder related
encoder: conformer
encoder_conf:
    output_size: 512    # dimension of attention
    attention_heads: 8
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 12      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d # encoder input type, you can chose conv2d, conv2d6 and conv2d8
    normalize_before: true
    cnn_module_kernel: 15
    use_cnn_module: True
    cnn_module_norm: 'layer_norm'
    activation_type: 'swish'
    pos_enc_layer_type: 'rel_pos'
    selfattention_layer_type: 'rel_selfattn'

# decoder related
decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1     # label smoothing option
    length_normalized_loss: false

dataset_conf:
    filter_conf:
        max_length: 1200
        min_length: 10
        token_max_length: 100
        token_min_length: 1
    resample_conf:
        resample_rate: 16000
    speed_perturb: false
    fbank_conf:
        num_mel_bins: 80
        frame_shift: 10
        frame_length: 25
        dither: 1.0
    spec_aug: true
    spec_aug_conf:
        num_t_mask: 2
        num_f_mask: 2
        max_t: 50
        max_f: 30
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    sort: true
    sort_conf:
        sort_size: 1000  # sort_size should be less than shuffle_size
    batch_conf:
        batch_type: 'static' # static or dynamic
        batch_size: 1

ipu_conf:
    seed: 1234
    available_memory_propotion: [0.1, 0.1, 0.15, 0.11]
    local_batch_size: 2
    num_replicas: 4
    gradient_accumulation: 512
    enable_half_partials: true
    enable_stochastic_rounding: true
    optimizer_state_offchip: false
    device_iterations: &device_iterations 1
    enable_synthetic_data: false
    enable_profile: false
    profile_path: './profiles/'
    executable_cache: './exec_cache'
    pipeline: 
        - ['encoder.encoders__2', 1]
        - ['encoder.encoders__8', 2]
        - ['decoder.decoders__3', 3]


max_epoch: 26
log_interval: 100

optim: adam
optim_conf:
    lr: 0.001
    loss_scaling: 1024.0
    max_grad_norm: 5.0
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 5000
    device_factor: *device_iterations
precision: float16

enable_validation: true

