config: ???
test_data: ???
checkpoint: ???
dict: ???
result_file: ???
gpu: -1
data_type: 'raw' # 'raw' or 'shared'
batch_size: 1

decoding:
    mode: 'attention' # 'attention', 'ctc_greedy_search', 'ctc_prefix_beam_search', 'attention_rescoring'
    ctc_weight: 0.0
    penalty: 0.0
    chunk_size: -1 # Specify decoding_chunk_size if it's a unified dynamic chunk trained model, -1 for full chunk
    num_left_chunks: -1
    reverse_weight: 0.0
    beam_size: 10

simulate_streaming: false
