config: ???
test_data: ???
checkpoint: ???
dict: ???
gpu: -1
data_type: 'raw' # 'raw' or 'shared'
batch_size: 1

decoding:
    mode: 'attention' # 'attention', 'ctc_greedy_search', 'ctc_prefix_beam_search', 'attention_rescoring'
    ctc_weight: 0.0
    penalty: 0.0
    chunk_size: -1
    num_left_chunks: -1
    reverse_weight: 0.0

simulate_streaming: false
