name: Build Wheels

on:
  pull_request:

env:
  BINDING_DIR: runtime/binding/python

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
        with:
          python-version: '3.6'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.5.0
        env:
          CIBW_BUILD_VERBOSITY: 1
          # Only build on CPython 3.6
          CIBW_BUILD: "cp36-*"
          # Disable building PyPy wheels on all platforms
          # Skip 32-bit builds
          CIBW_SKIP: "pp* *-win32 *-manylinux_i686 *-musllinux_*"
        with:
          package-dir: ${{ env.BINDING_DIR }}
          output-dir: wheelhouse

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: ./wheelhouse/

      # - uses: actions/upload-artifact@v2
      #   with:
      #     path: ./wheelhouse/*.whl
