package(default_visibility = ["//visibility:public"])

cc_library(
    name = 'utils',
    srcs = ['utils.cc'],
    hdrs = [
        'blocking_queue.h',
        'utils.h'
    ],
    deps = [
    ],
)

